### ISSUE TITLE
Spells from non-system compendium show up in items tab.

### ISSUE THREAD

**Issue by Red5Phil** [League-of-Foundry-Developers/compendium-browser#10] opened 2021-03-05 00:24 UTC
I am using foundry 0.7.9 on Forge with the dnd5e system. SRD spells show up under the spells tab as expected, but any spells I have in other compendia, particularly ones I’ve imported via a shared world compendium, show up in both the spell and item tabs. This happens with all spells in the non-SRD compendium, including ones that are both compedia.

**Comment by spetzel2020** [comment] 2021-03-12 02:31
Thanks and sorry for the delayed response. I'm bug fixing now and will take a look at this.

**Comment by spetzel2020** [comment] 2021-03-12 22:27
I think this is an even more generic problem, stemming from a loose test at `compendium-browser.js#504` . The problem is that there are multiple "types" that are considered actual items, (like weapon, consumable etc). Rather than test for each of them I will just exclude spell, feat, and class.

To fix in 0.4.4.

**Comment by spetzel2020** [comment] 2021-03-15 20:07
Fixed in 0.4.5

**Comment by spetzel2020** [comment] 2021-03-17 19:28
Released in 0.4.5; update from the module list or use manifest https://github.com/League-of-Foundry-Developers/compendium-browser/releases/download/latest/module.json

**Closed** 2021-03-17 19:28 UTC
Labels: bug
